### PR TITLE
fixup! Edit and adjust grammar

### PR DESCRIPTION
**Pull request by Kinnara-icz**

### CODE REVIEW

**Review by Kinnara-icz — COMMENTED** [review]
"Vị dụ : Alan Walker - Faded.m4a\nVideo Alan Walker - Faded (480p).mp4"

"Vị dụ" This is wrong or unclear word so I have changed it to "example" - "Ví Dụ"

They will themselves understand as a particular theme_mode of interpretation that is not common

**Comment by MSOB7YY** [comment]
hey thank u so much!! 
about "supremacy" it should be "Quyền cao" tho

**Comment by Kinnara-icz** [comment]
> hey thank u so much!! 
> about "supremacy" it should be "Quyền cao" tho

fixed

**Comment by MSOB7YY** [comment]
yattaa

**Comment by MSOB7YY** [comment]
@Kinnara-icz why did u close lmao

**Comment by Kinnara-icz** [comment]
> @Kinnara-icz why did u close lmao

skull

**Pull request merged**
