### PR TITLE
Update langs.json

### PR DESCRIPTION
**Pull request by Kiimby**
Spanish info for language added

### CODE REVIEW

**Comment by MSOB7YY** [comment]
hello, there is a Spanish translation in #11, can u elaborate what exactly does this pr contains? i can only see the lang.json changes, no actual keys

**Comment by Kiimby** [comment]
Hi! I'm still working in the spanish .json

Looks like i made an error updating the lang.json 

Sorry 😅

**Comment by MSOB7YY** [comment]
@Kiimby lmao no worriess
just keep in mind that there is already a Spanish translation in #11, better to review/improve it than creating a new translation, thank u so much tho!

**Comment by MSOB7YY** [comment]
any updates? im going to close, if u finished reviewing Spanish on #11 then open a new pr, thank u so much for the help tho <3

**Pull request closed without merging**
