### PR TITLE
Polishing Simplified Chinese Translations

### PR DESCRIPTION
**Pull request by monstorix**
Hopefully this can (partially) solve #33

The original Chinese (Simplified) translation may be generated by machine translation and therefore have quite a few unnatural words and phrases. This PR synced the new keys from the English translations and further adjusted the translation.

However, in the long run, it may be more beneficial to set up a translation platform such as [Weblate](https://hosted.weblate.org) to handle key-value synchronisation automatically. Manually comparing Json key-value pairs is not very efficient as the strings continue to grow.

### CODE REVIEW

**Comment by MSOB7YY** [comment]
really thank u sosososo muchh, sadly i cant detect if its machine generated or not so im glad for ur contribution 💖

i have tried looking into weblate/crowdin before but the setup was kinda pain so i just left it, might rethink about this again.
u should see the differences with any git compatible program, like vscode so its not really manual.. unless on phones i guess, will try to relook into weblate

**Comment by monstorix** [comment]
> u should see the differences with any git compatible program, like vscode so its not really manual.

Yes. I've actually used the git diff and some json comparison tool to solve this. Although to keep the file clean, I still inserted the new strings individually to the corresponding area, since the strings are alphabetically sorted.

**Comment by MSOB7YY** [comment]
@monstorix i have checked weblate and crowdin again and they both are not free. not sure if there is other good alternatives for this

on weblate u can setup a project for free but u need to send them a request with your *open source* project and other requirements... idk

**Comment by monstorix** [comment]
@MSOB7YY 

The official instance of Weblate did require a project to be fully libre to use its service for free, with a provement process needed. There are some other instances only require the translation files itself using a FOSS-compatible licence, like [Codeberg Weblate](https://translate.codeberg.org/)

Idk if the translation repo using any FOSS or CC licence?

**Comment by MSOB7YY** [comment]
@monstorix i have managed to upload translations [there](https://translate.codeberg.org/projects/namida-translations/namicomponent/), but the configuring process is quite complicated, it shows everything as translated and i cant find a way to sync from a base file.. idk yet

**Comment by monstorix** [comment]
@MSOB7YY I'm trying to install Weblate locally and test to see if I can add items correctly, if I make progress I'll update the configuration steps here.

**Comment by monstorix** [comment]
> it shows everything as translated and i cant find a way to sync from a base file.. idk yet

@MSOB7YY I've just found that Codeberg has a [detailed doc page](https://docs.codeberg.org/codeberg-translate/getting-started/) for weblate configuration. I've used the above steps to test on my local instance, it was successful.

The current component on Codeberg doesn't seem to be configured correctly. You can delete it and add it again by following the doc. However, the following things still need to be taken care of:

1. When the system asks what files to be imported, Choose the "File format JSON..." one.
choose_1

2. On the page where you fill in the detailed configuration information, you will also need to fill in the relevant 3 items as shown in the figure below, to make the English translation file being the base. Other than that, theres's no need to change any other things that the doc didn't mentioned.
base_1

3. The documentation also describes how to synchronise changes to the repository via Webhook. Simply follow the steps to configure it.

If everyting is right, the translation page should turn out like this:
right

**Comment by monstorix** [comment]
For the permission warning, if the instance didn't give the choice to connect github, make a translation mirror repo on Codeberg then sync it with here seems easier (maybe codeberg only has a good gitea integration). 

Otherwise it's great. You can merge this PR now if there is no other conflict.

**Comment by MSOB7YY** [comment]
lmao i tried everything and in the end, using access token in push url fixed it, gonna solve conflicts and merge, thanks again

**Pull request merged**
