### PR TITLE
Add French language

### PR DESCRIPTION
**Pull request by yannouuuu**
Hello !!
Here's a French version of the application. If there's anything you'd like to correct, don't hesitate to contact me (I joined the Telegram discussion channel not long ago).

I have a simple request to improve my translation of these two lines : https://github.com/yannouuuu/namida-translations/blob/082325fb177340e55edb2e99c7fc87b23e0607e5/translations/fr_FR.json#L425-L426

What are their meanings because I've been looking for a long time with no result x)

Stay tuned!

### CODE REVIEW

**Comment by MSOB7YY** [comment]
yoo yanounnouu
lotta thanks for the frenchie translation! <3
the lines u mentioned are basically a sound **pitch** and lyrics if they're **plain** text or synced
Screenshot_20240210-015323_Namida

also welcome to the group! will merge the pr soon before the release, thank u so much again!

**Comment by yannouuuu** [comment]
Thanks!!! I understand better now lol
That's it, I've corrected it, if I need to correct it according to the evolution of the app I'll stay available don't hesitate (ping me on discord or github :) )

**Comment by MSOB7YY** [comment]
thank u!! worth to mention that u can load ur json file inside namida by pressing "`local`" after opening languages dialog, thay way u can preview ur translation in real time.
other than that things seems nice, gonna merge before the next release.

**Comment by yannouuuu** [comment]
I wonder why I didn't do that earlier, thanks for the tips I was able to correct and improve for more understanding for your users!

**Pull request merged**
