### PR TITLE
I added the translation for es_CO, He and zh_Hant

### PR DESCRIPTION
**Pull request by xqsart**
# 🌎 Hello, World! 🌍

I am sending the translation contribution of the following languages: 

- 🇨🇴 **Spanish (Colombia)**
- 🇮🇱 **Hebrew (Israel)**
- 🇹🇼 **Traditional Chinese (Taiwan)**
- 🇨🇳 **Simplified Chinese (China)**

I have followed the steps indicated in the README.md file and created the corresponding files in the translations folder. I have copied the keys from the en_US.json file and translated them into the corresponding language. I hope that my contribution will be useful for the project and that it will be reviewed and approved. Thank you. 

## 📁 Files created

| Language | File name |
| -------- | --------- |
| Spanish (Colombia) | es_CO.json |
| Hebrew (Israel) | he_IL.json |
| Traditional Chinese (Taiwan) | zh_Hant.json |
| Simplified Chinese (China) | zh_Hans.json |

### CODE REVIEW

**Comment by MSOB7YY** [comment]
wait what 😳 did you just add translation for.. 4 LANGUAGES?? 😳😳
are they actually hand made translation or machine/ai generated? i mean it's quite weird to master 3 languages to be as native? i will accept the pr bothways but just wanted to know

also thanks a lot for the organized pr details, i like it

**Comment by xqsart** [comment]
:fire: **What is this?** :fire: Apparently it requests to add a few lines of the Spanish language Spain which is in incorrect format, it also adds that the country of Spanish-Spain is Latin America which is another error since Spain is a European country and finally it does not add the translated keys. In general #12 is garbage. :poop:

The Spanish from es-🇨🇴  that I sent is in correct format and all its keys are translated. 🍻 💀

**Comment by xqsart** [comment]
The Spanish that I sent corresponds to the Spanish of Colombia represented with its ISO 639-1 and ISO 3166-1 code, #12 is 🗑️

**Comment by MSOB7YY** [comment]
thank u so much and sorry for the delay
for some reasons **im not going to add hebew tho**, if u dislike that and prefer either all or none pls let me know, thanks again.

**Pull request merged**
